# Generated by Django 4.0 on 2021-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('schedule', models.DateField(blank=True, null=True)),
                ('existing', models.CharField(max_length=255)),
                ('how_do_you_hear', models.CharField(max_length=255)),
                ('referral_name', models.CharField(max_length=255)),
                ('comments', models.TextField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsInquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
