# Generated by Django 4.0 on 2021-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_service_alter_bookanestimate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookanestimate',
            name='service',
            field=models.ManyToManyField(related_name='services', to='applications.Service'),
        ),
    ]
